ignoredBuiltDependencies:
  - '@thaunknown/yencode'
  - bufferutil
  - electron
  - node-datachannel
  - protobufjs
  - utf-8-validate
  - utp-native

onlyBuiltDependencies:
  - '@paymoapp/electron-shutdown-handler'
  - esbuild
